### ISSUE TITLE
Seeing Promoted posts even when disabled

### ISSUE THREAD

**Issue by baggachipz** [bermudalocket/Tweaks-for-Reddit#32]
<img width="487" alt="Screen Shot 2021-06-08 at 9 41 27 AM" src="https://user-images.githubusercontent.com/617372/121195879-fee65400-c83d-11eb-9154-4ad645d98cb2.png">

I've tried reloading several times, and they still show. I forgot how much I hated them! :)

**Comment by baggachipz** [comment]
Additional details:
- Safari Version 14.1 (16611.1.21.161.3)
- macOS Big Sur 11.3 (M1 chip)

**Comment by bermudalocket** [comment]
Hi @baggachipz, I'm having trouble reproducing this. I have an idea re: what's causing it but since I can't reproduce it I'm not sure I'm on the right track.

I'm pretty sure promoted posts are being loaded into DOM async some time after the document emits the ready event. A slow connection would explain why they're not being removed, as if my theory is correct, the promoted posts are being loaded _after_ the remove script runs. I could take a stab in the dark and rewrite the removal script(s) to continuously monitor the DOM using something like a MutationObserver, but if my theory is incorrect this solution is not a solution at all.

A few questions to help me out:

1. Are you seeing promoted posts consistently? I.e. every single time you load r/all, r/home, a subreddit, etc., or only sometimes?
2. Could you run a [speed test](https://www.speedtest.net/)? You don't have to give me exact results. I just need to know if your download speed is slow (< ~40 Mbps) or not (> ~40 Mbps)

**Comment by baggachipz** [comment]
It only happens on pages loaded with infinite scroll. So, the initial page load has no Promoted posts, but anything after that does. That says to me that when new content is loaded, that's when the Promoted posts aren't scrubbed for whatever reason. FWIW my connection is pretty fast, [this is over wifi](https://www.speedtest.net/result/11562689355).

**Comment by bermudalocket** [comment]
> So, the initial page load has no Promoted posts, but anything after that does.

Oh, that's much easier to solve. Reproduced & working on it!
